import {
  AdjustmentsVerticalIcon,
  Battery50Icon,
  BookOpenIcon,
  CameraIcon,
  ChartBarIcon,
  CloudIcon,
  ClipboardDocumentCheckIcon,
  Cog6ToothIcon,
  CommandLineIcon,
  CpuChipIcon,
  CubeTransparentIcon,
  FilmIcon,
  GlobeAsiaAustraliaIcon,
  HomeIcon,
  LightBulbIcon,
  LinkIcon,
  MusicalNoteIcon,
  PencilSquareIcon,
  PhotoIcon,
  PlayIcon,
  PuzzlePieceIcon,
  ScaleIcon,
  SparklesIcon,
  VideoCameraIcon,
  ViewfinderCircleIcon,
  ArrowPathIcon,
  BoltIcon,
  EyeDropperIcon,
  Squares2X2Icon,
  GlobeAltIcon,
  PowerIcon,
  LinkSlashIcon,
  UserGroupIcon,
  ClockIcon,
} from '@heroicons/react/24/outline';

const icons = {
  AdjustmentsVerticalIcon,
  Battery50Icon,
  BookOpenIcon,
  CameraIcon,
  ChartBarIcon,
  CloudIcon,
  ClipboardDocumentCheckIcon,
  Cog6ToothIcon,
  CommandLineIcon,
  CpuChipIcon,
  CubeTransparentIcon,
  FilmIcon,
  GlobeAsiaAustraliaIcon,
  HomeIcon,
  LightBulbIcon,
  LinkIcon,
  MusicalNoteIcon,
  PencilSquareIcon,
  PhotoIcon,
  PlayIcon,
  PuzzlePieceIcon,
  ScaleIcon,
  SparklesIcon,
  VideoCameraIcon,
  ViewfinderCircleIcon,
  ArrowPathIcon,
  BoltIcon,
  EyeDropperIcon,
  Squares2X2Icon,
  GlobeAltIcon,
  PowerIcon,
  LinkSlashIcon,
  UserGroupIcon,
  ClockIcon,
};

export function Icon({ name, className }) {
  const Component = icons[name] || LinkSlashIcon;
  return <Component className={className} aria-hidden />;
}
